// INTRO v3 (spec/intro-v3.md) - starts as a copy of INTRO v2; iterate
// here freely: v1 and v2 stay locked and byte-identical. Scene kinds are the
// v3 copies (IntroV3Scenes.tsx), so visual edits never touch v2 either.
import { Shot, validateShots } from "./types";

export const INTRO3_SHOTS: Shot[] = validateShots([
  {
    id: "N-0",
    start: 0,
    end: 6,
    lines: [],
    vo: "Verana. The open trust infrastructure for the verifiable internet.",
    visual: { kind: "brand-open" },
    tone: "light",
  },
  {
    id: "N-1",
    start: 6,
    end: 24,
    lines: [
      "Decentralized digital identity is becoming a reality.",
      "eIDAS 2.0 in Europe, and the W3C standards. We build on both.",
    ],
    vo: "Decentralized digital identity is becoming a reality: eIDAS 2.0 in Europe, and the W3C standards ecosystem. We build on both.",
    visual: { kind: "foundations-v3" },
    tone: "light",
    // The beat-3 band takes the lower third at 9.2s (scene-relative).
    textFadeOut: [8.2, 9.2],
  },
  {
    id: "N-2",
    start: 24,
    end: 34,
    lines: [
      "These technologies have proven their worth.",
      "The next challenges: scalability, interoperability, and monetization.",
    ],
    vo: "These technologies have proven their worth. The next challenges: scalability, interoperability, and monetization.",
    visual: { kind: "silos-v3" },
    tone: "dark",
  },
  {
    id: "N-3",
    start: 34,
    end: 40,
    lines: ["Have you ever wondered...", "who is really behind this service?"],
    vo: "Have you ever wondered... who is really behind this service?",
    visual: { kind: "login-glitch" },
    tone: "dark",
  },
  {
    id: "N-4",
    start: 40,
    end: 47,
    lines: ["And behind this AI agent?"],
    vo: "And behind this AI agent?",
    visual: { kind: "agent-flicker" },
    tone: "dark",
  },
  {
    id: "N-5",
    start: 47,
    end: 53,
    lines: ["And when you receive a credential...", "is it real? Is the issuer accredited?"],
    vo: "And when you receive a credential... is it real? Is the issuer accredited?",
    visual: {
      kind: "qr-scan-phone",
      asset: "clips/intro-issuer-unaccredited",
      qrLabel: "Scan this QR to get your credential",
      phoneSide: "right",
    },
    duck: true,
    tone: "dark",
  },
  {
    id: "N-6",
    start: 53,
    end: 59,
    lines: ["And when a service asks for your ID...", "is it even allowed to ask?"],
    vo: "And when a service asks for your ID: is it even allowed to ask?",
    visual: {
      kind: "qr-scan-phone",
      asset: "clips/intro-verifier-unaccredited",
      qrLabel: "Scan this QR to present your ID",
      phoneSide: "left",
    },
    duck: true,
    tone: "dark",
  },
  {
    id: "N-7",
    start: 59,
    end: 65,
    lines: ["And finally... how do you, or your AI agent,", "find a trusted service?"],
    vo: "And finally: how do you, or your AI agent, find a trusted service?",
    visual: { kind: "ecosystem-search-v3" },
    tone: "dark",
  },
  {
    id: "N-8a",
    start: 65,
    end: 75,
    lines: [
      "Official trust lists exist.",
      "A solution is needed to scale, monetize, and address private ecosystems.",
    ],
    vo: "Official trust lists exist. But a solution is needed to scale, monetize and address the private ecosystems.",
    visual: { kind: "trust-lists-v3" },
    tone: "light",
  },
  {
    id: "N-8b",
    start: 75,
    end: 83,
    lines: ["Verana is that bridge.", "Independent, at scale, and across ecosystems."],
    vo: "Verana is that bridge. Independent, at scale, and across ecosystems.",
    visual: { kind: "brand-reveal" },
    tone: "light",
  },
  {
    id: "N-9a",
    start: 83,
    end: 93,
    lines: [
      "Build your own sovereign ecosystem, freely.",
      "Your rules, your business model.",
    ],
    vo: "Build your own sovereign ecosystem, freely, on Verana's public, privacy-preserving infrastructure: your rules, your business model.",
    visual: { kind: "build-eco-v3" },
    tone: "light",
  },
  {
    id: "N-9b",
    start: 93,
    end: 106,
    lines: [],
    vo: "Then build your service: choose the ecosystems you would like to join, on Verana, or on other trust lists. Choose your personal wallet. And bridge to other ecosystems.",
    visual: { kind: "build-service-v3" },
    tone: "light",
  },
  {
    id: "N-10",
    start: 106,
    end: 123,
    lines: [],
    vo: "In essence: Verana enables trust to scale. Not just within one ecosystem: across the entire digital economy. Verana dot io.",
    visual: { kind: "verana-close-v3" },
    tone: "light",
  },
]);

export const INTRO3_END = 123;
