// INTRO v3 (spec/intro-v3.md) - starts as a copy of INTRO v2; iterate
// here freely: v1 and v2 stay locked and byte-identical. Scene kinds are the
// v3 copies (IntroV3Scenes.tsx), so visual edits never touch v2 either.
import { Shot, validateShots } from "./types";

export const INTRO3_SHOTS: Shot[] = validateShots([
  {
    id: "N-0",
    start: 0,
    end: 6,
    lines: [],
    vo: "Verana. The open trust infrastructure for the verifiable internet.",
    visual: { kind: "brand-open" },
    tone: "light",
  },
  {
    id: "N-1",
    start: 6,
    end: 24,
    lines: [],
    vo: "Verifiable credentials are becoming a reality. The foundations are laid: issuer, holder, verifier, one trust triangle. And implementations are arriving in every sector: each ecosystem potentially bringing value to the entire digital economy.",
    visual: { kind: "foundations-v3" },
    tone: "light",
  },
  {
    id: "N-2",
    start: 24,
    end: 43,
    lines: [],
    vo: "Let's have a look at the challenges of interconnecting ecosystems. One: create new ecosystems at will, and monetize them. Two: scale across borders. Three: authenticate mutually. And four: discovery: find trusted services, anywhere.",
    visual: { kind: "silos-v3" },
    tone: "dark",
  },
  {
    id: "N-3",
    start: 43,
    end: 61,
    lines: [],
    vo: "Challenge one: scale, by creating ecosystems. How do we create new trust registries at will: publish schemas and accreditation lists, define business models, and make each ecosystem publicly discoverable, interconnectable, and joinable?",
    visual: { kind: "create-eco-q-v3" },
    tone: "dark",
  },
  {
    id: "N-4",
    start: 61,
    end: 71,
    lines: [],
    vo: "Challenge two: scale, cross-border. How do we recognize and onboard ecosystems from any country, and any sector?",
    visual: { kind: "cross-border-q-v3" },
    tone: "dark",
  },
  {
    id: "N-5",
    start: 71,
    end: 81,
    lines: [],
    vo: "Challenge three: mutual authentication. How do services and AI agents from different countries identify each other, and trust each other?",
    visual: { kind: "mutual-auth-v3" },
    tone: "dark",
  },
  {
    id: "N-6",
    start: 81,
    end: 88,
    lines: [],
    vo: "Challenge four, and finally: discovery. How do we search the graph of trusted services?",
    visual: { kind: "ecosystem-search-v3" },
    tone: "dark",
  },
  {
    id: "N-8b",
    start: 88,
    end: 100,
    lines: [],
    vo: "Verana answers all of this. Sovereign ecosystems, verifiable identity, one public Trust Graph. Open, neutral, cross-border, owned by no one.",
    visual: { kind: "answers-v3" },
    tone: "light",
  },
  {
    id: "N-9a",
    start: 100,
    end: 116,
    lines: [],
    vo: "Building your own sovereign ecosystem trust registry in Verana is straightforward. Start by creating your trust registry, publish your Ecosystem Governance Framework, your credential schemas and business models. Onboard your ecosystem participants. Your ecosystem exists, and is discoverable.",
    visual: { kind: "build-eco-tree-v3" },
    tone: "light",
  },
  {
    id: "N-9b",
    start: 116,
    end: 139,
    lines: [],
    vo: "Then deploy your services and AI agents. Choose your business wallet. Join ecosystems, on Verana or on other trust lists. Attach their credentials to your services: you are now visible in the Trust Graph. And issue and verify credentials, to personal wallets, AI agents, or any service with a wallet.",
    visual: { kind: "build-service-v3" },
    tone: "light",
  },
  {
    id: "N-9c",
    start: 139,
    end: 154,
    lines: [],
    vo: "You are now part of the Trust Graph. Any person, service, or AI agent can find you, mutually authenticate with verifiable credentials, and connect. Trust, established before the first message.",
    visual: { kind: "connect-v3" },
    tone: "light",
  },
  {
    id: "N-9d",
    start: 154,
    end: 174,
    lines: [],
    vo: "Behind Verana: open specifications, built exclusively on open standards. Open-source software. And a non-profit foundation, managed by its community. Want to contribute? Join the Foundation: it is free for contributors. Join a working group, or create your own.",
    visual: { kind: "foundation-v3" },
    tone: "light",
  },
  {
    id: "N-10",
    start: 174,
    end: 189,
    lines: [],
    vo: "In essence: Verana enables trust to scale. Not just within one ecosystem: across the entire digital economy. Try it yourself, on the public playground. Verana dot io.",
    visual: { kind: "verana-close-v3" },
    tone: "light",
  },
]);

export const INTRO3_END = 189;
