// Asset resolution with graceful placeholders. The manifest is generated by
// scripts/sync-assets.mjs from what is actually on disk (public/assets/), is
// fetched once in each composition's calculateMetadata, and flows down via
// context. Any id missing from the manifest renders a labeled placeholder,
// so the project renders end to end before any media is synced or captured.
import React, { createContext, useContext } from "react";
import { AbsoluteFill, Img, OffthreadVideo, staticFile } from "remotion";
import { theme } from "../theme";

export type AssetManifest = Record<string, string>;

export const AssetContext = createContext<AssetManifest>({});

export const useAsset = (id: string): string | null => {
  const manifest = useContext(AssetContext);
  const rel = manifest[id];
  return rel ? staticFile(rel) : null;
};

export const fetchManifest = async (): Promise<AssetManifest> => {
  try {
    const res = await fetch(staticFile("assets/manifest.json"));
    if (!res.ok) return {};
    return (await res.json()) as AssetManifest;
  } catch {
    return {};
  }
};

/** Full-bleed placeholder naming the missing asset (kept deliberately ugly). */
export const Placeholder: React.FC<{ id: string; label?: string }> = ({ id, label }) => (
  <AbsoluteFill
    style={{
      background: `repeating-linear-gradient(45deg, #1e2433 0 40px, #232a3d 40px 80px)`,
      alignItems: "center",
      justifyContent: "center",
      fontFamily: theme.font,
    }}
  >
    <div style={{ color: theme.faint, fontSize: 30, textAlign: "center", lineHeight: 1.5 }}>
      <div style={{ fontSize: 22, letterSpacing: 4, textTransform: "uppercase" }}>placeholder</div>
      <div style={{ color: "#cbd5e1", fontFamily: theme.mono }}>{id}</div>
      {label ? <div style={{ fontSize: 24, marginTop: 8 }}>{label}</div> : null}
    </div>
  </AbsoluteFill>
);

export const AssetImg: React.FC<{
  id: string;
  style?: React.CSSProperties;
  cover?: boolean;
}> = ({ id, style, cover = true }) => {
  const src = useAsset(id);
  if (!src) return <Placeholder id={id} />;
  return (
    <Img
      src={src}
      style={{ width: "100%", height: "100%", objectFit: cover ? "cover" : "contain", ...style }}
    />
  );
};

export const AssetVideo: React.FC<{
  id: string;
  label?: string;
  style?: React.CSSProperties;
}> = ({ id, label, style }) => {
  const src = useAsset(id);
  if (!src) return <Placeholder id={id} label={label} />;
  return (
    <OffthreadVideo
      src={src}
      muted
      style={{ width: "100%", height: "100%", objectFit: "cover", ...style }}
    />
  );
};
